### PR TITLE
updated "time" to say 시간

### PR DESCRIPTION
**Pull request by shinjoe**
Hey, awesome app! I took a quick skim at the KO localization, and found a typo. I'm guessing @VitalikL might be most appropriate for this PR?

### CODE REVIEW

**Comment by imasaru** [comment]
@shinjoe I think I know who you are :smirk: 

It could have been a copy-paste error... not sure.

What do you think overall? My method of making the Korean localization was translating from English, retranslating from Chinese and Japanese, and using Naver for the rest :sweat_smile: a lot of work

Also, you may want to add Heberti as well.

**Comment by shinjoe** [comment]
@imasaru 😄

Overall, I think its really good. In fact, I did some more research yesterday, and it turns out that 시각 is used when referring to an exact time, which is the context used in this app. Therefore, feel free to close this merge request as `won't-fix; not a bug`. Both translations would work, but yours is more accurate. 😎

Adding @hebertialmeida as requested.

**Comment by VitalikL** [comment]
Thanks @shinjoe ! Curious are you an iOS dev yourself?
PS: love your dharma initiatives logo :D

**Comment by shinjoe** [comment]
Naw, just someone who enjoys the app. Thanks!

**Comment by shinjoe** [comment]
Follow-up question. Looks like CI is broken: `Fix WWDRCA Certificate` -- how involved would it be to get Travis working again?

**Comment by VitalikL** [comment]
This is because of Two-Factor Authentication. I plan prod deploy this week so it isnt Travis issue but rather Apple's

**Comment by shinjoe** [comment]
Gotcha, thanks for the clarification. Sounds good!

**Pull request merged**
