### PR TITLE
Upgrading codebase to latest Swift and Xcode

### PR DESCRIPTION
**Pull request by hebertialmeida**
### Changes
- Upgrading from Swift 3 -> 4 -> 5
- Upgrading from Xcode 10 -> 11.3
- Upgrading dependencies to latest version
- Removed deprecated `JSQWebViewController`
- iOS 13 Fixes

### Screnshots
Screen Shot 2020-02-15 at 12 15 12 AM
Screen Shot 2020-02-15 at 12 15 17 AM
Screen Shot 2020-02-15 at 12 15 23 AM
Screen Shot 2020-02-15 at 12 15 28 AM
Screen Shot 2020-02-15 at 12 15 31 AM
Screen Shot 2020-02-15 at 12 15 35 AM

### CODE REVIEW

**Comment by hebertialmeida** [comment]
@VitalikL Could you review that?

**Comment by VitalikL** [comment]
@hebertialmeida On it!

**Comment by VitalikL** [comment]
@hebertialmeida Everything looks and works fine except for the font size toggle. On a fresh run it does not set the default size for some reason

Screen Shot 2020-04-05 at 3 05 29 PM

**Review by VitalikL — APPROVED** [review]
See the issue with the default font size toggle

**Comment by hebertialmeida** [comment]
This issue exists in the current version, it is not intended to be fixed by this PR. The main focus here is to upgrade the dependencies, Swift and Xcode version.

**Comment by VitalikL** [comment]
👍 Lets merge it then.

**Pull request merged**
